all : run
 
run : main.cpp
	g++ -std=c++20 -o run -L .. -lall -I .. -I ../../evmone_v1/include/ -I ../../evmone_v2/include/ -I ../../evmc/include/ -I ../../intx/include/ -I ../../keccak/include main.cpp
